// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	db, cleanup, err := InitDB()
	if err != nil {
		return nil, nil, err
	}
	mData := &MData{
		DB: db,
	}
	bData := &BData{
		MData: mData,
	}
	injector := &Injector{
		DB:      db,
		Service: bData,
	}
	return injector, func() {
		cleanup()
	}, nil
}
